# Generated by Django 3.0.8 on 2020-08-06 21:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0007_auto_20200806_2123'),
        ('users', '0005_auto_20200806_2123'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PayOut', 'Вывод средств'), ('PayIn', 'Пополнение счета'), ('Buy', 'Покупка ценных бумаг'), ('BuyCard', 'Покупка ценных бумаг с банковской карты'), ('Sell', 'Продажа ценных бумаг'), ('Dividend', 'Получение дивидендов'), ('BrokerCommission', 'Комиссия брокера'), ('ServiceCommission', 'Комиссия за обслуживание'), ('MarginCommission', 'Комиссия за маржинальную торговлю'), ('Tax', 'Налог'), ('TaxBack', 'Налоговый вычет/корректировка налога'), ('TaxDividend', 'Налог на дивиденды'), ('Unknown', 'Неизвестен')], default='Unknown', max_length=30, verbose_name='Тип')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('is_margin_call', models.BooleanField(default=False)),
                ('payment', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Оплата')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.CurrencyInstrument', verbose_name='Валюта')),
                ('investment_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='users.InvestmentAccount', verbose_name='Инвестиционный счет')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_operations.operation_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='CommissionOperation',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.Operation')),
            ],
            options={
                'verbose_name': 'Комиссия',
                'verbose_name_plural': 'Комиссии',
            },
            bases=('operations.operation',),
        ),
        migrations.CreateModel(
            name='DividendOperation',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.Operation')),
                ('tax', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(0, 'Налог должен быть отрицательным числом или 0')], verbose_name='Налог')),
                ('tax_date', models.DateTimeField(verbose_name='Дата налога')),
            ],
            options={
                'verbose_name': 'Дивиденды',
                'verbose_name_plural': 'Дивиденды',
            },
            bases=('operations.operation', models.Model),
        ),
        migrations.CreateModel(
            name='PayInOperation',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.Operation')),
            ],
            options={
                'verbose_name': 'Пополнение средств',
                'verbose_name_plural': 'Пополнения средств',
            },
            bases=('operations.operation',),
        ),
        migrations.CreateModel(
            name='PayOutOperation',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.Operation')),
            ],
            options={
                'verbose_name': 'Вывод средств',
                'verbose_name_plural': 'Выводы средств',
            },
            bases=('operations.operation',),
        ),
        migrations.CreateModel(
            name='PurchaseAndSaleOperation',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.Operation')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('commission', models.DecimalField(decimal_places=4, default=0, max_digits=16, verbose_name='Комиссия')),
                ('_id', models.CharField(max_length=32, verbose_name='ID')),
                ('deal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='market.Deal', verbose_name='Сделка')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.InstrumentType', verbose_name='Ценная бумага')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('operations.operation', models.Model),
        ),
        migrations.CreateModel(
            name='TaxBackOperation',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.Operation')),
            ],
            options={
                'verbose_name': 'Возврат налога',
                'verbose_name_plural': 'Возвраты налога',
            },
            bases=('operations.operation',),
        ),
        migrations.CreateModel(
            name='TaxOperation',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.Operation')),
            ],
            options={
                'verbose_name': 'Налог',
                'verbose_name_plural': 'Налоги',
            },
            bases=('operations.operation',),
        ),
        migrations.CreateModel(
            name='MarginCommissionOperation',
            fields=[
                ('commissionoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.CommissionOperation')),
            ],
            options={
                'verbose_name': 'Комиссия за маржинальную торговлю',
                'verbose_name_plural': 'Комиссии за маржинальную торговлю',
            },
            bases=('operations.commissionoperation',),
        ),
        migrations.CreateModel(
            name='PurchaseOperation',
            fields=[
                ('purchaseandsaleoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.PurchaseAndSaleOperation')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
            bases=('operations.purchaseandsaleoperation',),
        ),
        migrations.CreateModel(
            name='SaleOperation',
            fields=[
                ('purchaseandsaleoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.PurchaseAndSaleOperation')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
            bases=('operations.purchaseandsaleoperation',),
        ),
        migrations.CreateModel(
            name='ServiceCommissionOperation',
            fields=[
                ('commissionoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.CommissionOperation')),
            ],
            options={
                'verbose_name': 'Сервисная комиссия',
                'verbose_name_plural': 'Сервисные комиссии',
            },
            bases=('operations.commissionoperation',),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=32, unique=True, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество шт.')),
                ('price', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Цена/шт.')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.PurchaseAndSaleOperation', verbose_name='Операция')),
            ],
            options={
                'verbose_name': 'Транзакции',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=8, max_digits=9, verbose_name='Доля')),
                ('co_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='users.CoOwner', verbose_name='Совладелец')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='operations.PurchaseAndSaleOperation', verbose_name='Операция')),
            ],
            options={
                'verbose_name': 'Доля в операции',
                'verbose_name_plural': 'Доли в операциях',
                'ordering': ['pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.UniqueConstraint(fields=('type', 'date', 'investment_account'), name='unique operation'),
        ),
        migrations.AddField(
            model_name='dividendoperation',
            name='deal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='market.Deal', verbose_name='Сделка'),
        ),
        migrations.AddField(
            model_name='dividendoperation',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.InstrumentType', verbose_name='Ценная бумага'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.UniqueConstraint(fields=('operation', 'co_owner'), name='unique_co_owner_op'),
        ),
    ]
