# Generated by Django 3.0.8 on 2020-08-12 11:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('iso_code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True, verbose_name='Код')),
                ('abbreviation', models.CharField(max_length=16, verbose_name='Символ')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('is_margin_call', models.BooleanField(default=False)),
                ('payment', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Оплата')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=8, max_digits=9, verbose_name='Доля')),
            ],
            options={
                'verbose_name': 'Доля в операции',
                'verbose_name_plural': 'Доли в операциях',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=32, unique=True, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество шт.')),
                ('price', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Цена/шт.')),
            ],
            options={
                'verbose_name': 'Транзакции',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.CreateModel(
            name='CommissionOperation',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.Operation')),
                ('type', models.CharField(choices=[('ServiceCommission', 'Service Commission'), ('MarginCommission', 'Margin Commission')], max_length=30, verbose_name='Тип операции')),
            ],
            options={
                'verbose_name': 'Комиссия',
                'verbose_name_plural': 'Комиссии',
            },
            bases=('operations.operation',),
        ),
        migrations.CreateModel(
            name='DividendOperation',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.Operation')),
                ('tax', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(0, 'Налог должен быть отрицательным числом или 0')], verbose_name='Налог')),
                ('tax_date', models.DateTimeField(verbose_name='Дата налога')),
            ],
            options={
                'verbose_name': 'Дивиденды',
                'verbose_name_plural': 'Дивиденды',
            },
            bases=('operations.operation', models.Model),
        ),
        migrations.CreateModel(
            name='PayOperation',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.Operation')),
                ('type', models.CharField(choices=[('PayIn', 'Pay In'), ('PayOut', 'Pay Out')], max_length=30, verbose_name='Тип операции')),
            ],
            options={
                'verbose_name': 'Пополнение/Вывод средств',
                'verbose_name_plural': 'Пополнения/Выводы средств',
            },
            bases=('operations.operation',),
        ),
        migrations.CreateModel(
            name='PrimaryOperation',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.Operation')),
                ('type', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=30, verbose_name='Тип операции')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('commission', models.DecimalField(decimal_places=4, default=0, max_digits=16, verbose_name='Комиссия')),
                ('_id', models.CharField(max_length=32, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Покупка/Продажа',
                'verbose_name_plural': 'Покупки/Продажа',
            },
            bases=('operations.operation', models.Model),
        ),
        migrations.CreateModel(
            name='TaxBackOperation',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.Operation')),
            ],
            options={
                'verbose_name': 'Возврат налога',
                'verbose_name_plural': 'Возвраты налога',
            },
            bases=('operations.operation',),
        ),
        migrations.CreateModel(
            name='TaxOperation',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.Operation')),
            ],
            options={
                'verbose_name': 'Налог',
                'verbose_name_plural': 'Налоги',
            },
            bases=('operations.operation',),
        ),
    ]
