# Generated by Django 3.0.8 on 2020-08-12 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        ('market', '0002_auto_20200812_1106'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='co_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='users.CoOwner', verbose_name='Совладелец'),
        ),
        migrations.AddField(
            model_name='operation',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.CurrencyInstrument', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='operation',
            name='investment_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='users.InvestmentAccount', verbose_name='Инвестиционный счет'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.PrimaryOperation', verbose_name='Операция'),
        ),
        migrations.AddField(
            model_name='share',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='operations.PrimaryOperation', verbose_name='Операция'),
        ),
        migrations.AddField(
            model_name='primaryoperation',
            name='deal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='market.Deal', verbose_name='Сделка'),
        ),
        migrations.AddField(
            model_name='primaryoperation',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.InstrumentType', verbose_name='Ценная бумага'),
        ),
        migrations.AddConstraint(
            model_name='payoperation',
            constraint=models.UniqueConstraint(fields=('type', 'date', 'investment_account'), name='unique pay operation'),
        ),
        migrations.AddField(
            model_name='dividendoperation',
            name='deal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dividends', to='market.Deal', verbose_name='Сделка'),
        ),
        migrations.AddField(
            model_name='dividendoperation',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.InstrumentType', verbose_name='Ценная бумага'),
        ),
        migrations.AddConstraint(
            model_name='commissionoperation',
            constraint=models.UniqueConstraint(fields=('type', 'date', 'investment_account'), name='unique commission operation'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.UniqueConstraint(fields=('operation', 'co_owner'), name='unique_co_owner_op'),
        ),
        migrations.AddConstraint(
            model_name='primaryoperation',
            constraint=models.UniqueConstraint(fields=('type', 'date', 'investment_account'), name='unique primary operation'),
        ),
    ]
