# Generated by Django 3.0.8 on 2020-08-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200819_1726'),
        ('operations', '0002_auto_20200818_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='co_owners',
            field=models.ManyToManyField(through='operations.Share', to='users.CoOwner'),
        ),
    ]
