# Generated by Django 3.0.8 on 2020-08-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20200816_0103'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.UniqueConstraint(condition=models.Q(dividend_tax_date__isnull=False), fields=('investment_account', 'type', 'instrument', 'dividend_tax_date'), name='unique_div_tax_date'),
        ),
    ]
