# Generated by Django 3.0.8 on 2020-08-16 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20200816_2338'),
        ('operations', '0003_auto_20200816_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='deal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='market.Deal', verbose_name='Сделка'),
        ),
    ]
