# Generated by Django 3.0.7 on 2020-07-06 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('abbreviation', models.CharField(max_length=16, verbose_name='Знак')),
                ('number_to_basic', models.PositiveSmallIntegerField(default=100, verbose_name='Количество меньшей валюты в большей')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыта сделка?')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_id', models.CharField(max_length=32, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество шт.')),
                ('price', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Цена/шт.')),
            ],
            options={
                'verbose_name': 'Транзакции',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figi', models.CharField(max_length=32, unique=True, verbose_name='FIGI')),
                ('ticker', models.CharField(max_length=16, unique=True, verbose_name='Ticker')),
                ('isin', models.CharField(max_length=32, verbose_name='ISIN')),
                ('min_price_increment', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Шаг цены')),
                ('lot', models.PositiveIntegerField(verbose_name='шт/лот')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PayOut', 'Вывод средств'), ('PayIn', 'Пополнение счета'), ('Buy', 'Покупка ценных бумаг'), ('BuyCard', 'Покупка ценных бумаг с банковской карты'), ('Sell', 'Продажа ценных бумаг'), ('Dividend', 'Получение дивидендов'), ('BrokerCommission', 'Комиссия брокера'), ('ServiceCommission', 'Комиссия за обслуживание'), ('Tax', 'Налог'), ('TaxBack', 'Налоговый вычет/корректировка налога'), ('TaxDividend', 'Налог на дивиденды')], max_length=30, verbose_name='Тип')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('is_margin_call', models.BooleanField(default=False)),
                ('payment', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Оплата')),
                ('status', models.CharField(choices=[('Done', 'Выполнено'), ('Decline', 'Отказано')], max_length=16, verbose_name='Статус')),
                ('secondary_id', models.CharField(max_length=32, verbose_name='ID')),
                ('instrument_type', models.CharField(blank=True, max_length=32, verbose_name='Тип инструмента')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('commission', models.DecimalField(decimal_places=4, max_digits=16, null=True, verbose_name='Комиссия')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.Currency', verbose_name='Валюта')),
                ('deal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.Deal', verbose_name='Сделка')),
                ('figi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='market.Stock', verbose_name='Ценная бумага')),
                ('investment_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.InvestmentAccount', verbose_name='Инвестиционный счет')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ('date',),
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='figi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.Stock', verbose_name='Ценная бумага'),
        ),
        migrations.AddField(
            model_name='deal',
            name='investment_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.InvestmentAccount', verbose_name='Инвестиционный счет'),
        ),
    ]
