# Generated by Django 3.0.8 on 2020-08-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
        migrations.CreateModel(
            name='DealIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Доход')),
            ],
            options={
                'verbose_name': 'Доход за сделку',
                'verbose_name_plural': 'Доходы за сделку',
            },
        ),
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('figi', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='FIGI')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('ticker', models.CharField(max_length=16, unique=True, verbose_name='Ticker')),
                ('type', models.CharField(choices=[('Stock', 'Акция'), ('Currency', 'Валюта'), ('Unknown', 'Неизвестен')], max_length=30, verbose_name='Тип')),
                ('iso_code', models.CharField(default='', max_length=3, verbose_name='Код')),
                ('abbreviation', models.CharField(default='', max_length=16, verbose_name='Знак')),
                ('isin', models.CharField(default='', max_length=32, verbose_name='ISIN')),
                ('min_price_increment', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Шаг цены')),
                ('lot', models.PositiveIntegerField(default=0, verbose_name='шт/лот')),
            ],
            options={
                'verbose_name': 'Торговый инструмент',
                'verbose_name_plural': 'Торговые инструменты',
            },
        ),
    ]
