# Generated by Django 3.0.7 on 2020-07-23 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='co_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='users.CoOwner', verbose_name='Совладелец'),
        ),
        migrations.AddField(
            model_name='share',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='market.Operation', verbose_name='Операция'),
        ),
        migrations.AddField(
            model_name='operation',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.Currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='operation',
            name='deal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='market.Deal', verbose_name='Сделка'),
        ),
        migrations.AddField(
            model_name='operation',
            name='figi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='market.Stock', verbose_name='Ценная бумага'),
        ),
        migrations.AddField(
            model_name='operation',
            name='investment_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='users.InvestmentAccount', verbose_name='Инвестиционный счет'),
        ),
        migrations.AddField(
            model_name='dealincome',
            name='co_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CoOwner', verbose_name='Совладелец'),
        ),
        migrations.AddField(
            model_name='dealincome',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Deal', verbose_name='Сделка'),
        ),
        migrations.AddField(
            model_name='deal',
            name='figi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.Stock', verbose_name='Ценная бумага'),
        ),
        migrations.AddField(
            model_name='deal',
            name='investment_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='users.InvestmentAccount', verbose_name='Инвестиционный счет'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.UniqueConstraint(fields=('operation', 'co_owner'), name='unique_co_owner_op'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.UniqueConstraint(fields=('type', 'date', 'investment_account'), name='unique operation'),
        ),
        migrations.AddConstraint(
            model_name='dealincome',
            constraint=models.UniqueConstraint(fields=('deal', 'co_owner'), name='unique deal co-owner'),
        ),
    ]
