# Generated by Django 3.0.8 on 2020-08-12 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        ('market', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealincome',
            name='co_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CoOwner', verbose_name='Совладелец'),
        ),
        migrations.AddField(
            model_name='dealincome',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Deal', verbose_name='Сделка'),
        ),
        migrations.AddField(
            model_name='deal',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.InstrumentType', verbose_name='Ценная бумага'),
        ),
        migrations.AddField(
            model_name='deal',
            name='investment_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='users.InvestmentAccount', verbose_name='Инвестиционный счет'),
        ),
        migrations.AddField(
            model_name='stockinstrument',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.Currency', verbose_name='Валюта'),
        ),
        migrations.AddConstraint(
            model_name='dealincome',
            constraint=models.UniqueConstraint(fields=('deal', 'co_owner'), name='unique deal co-owner'),
        ),
    ]
