# Generated by Django 3.0.7 on 2020-06-29 22:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('abbreviation', models.CharField(max_length=16, verbose_name='Знак')),
                ('number_to_basic', models.PositiveSmallIntegerField(default=100, verbose_name='Количество меньшей валюты в большей')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_id', models.CharField(max_length=32, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество шт.')),
                ('price', models.PositiveIntegerField(verbose_name='Цена/шт.')),
            ],
            options={
                'verbose_name': 'Транзакции',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.AddField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 22, 6, 4, 883007, tzinfo=utc), verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='is_margin_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operation',
            name='payment',
            field=models.IntegerField(default=1.0, verbose_name='Оплата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='secondary_id',
            field=models.CharField(default=1.0, max_length=32, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('Done', 'Выполнено'), ('Decline', 'Отказано')], default='', max_length=16, verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('PayOut', 'Вывод средств'), ('PayIn', 'Пополнение счета'), ('Buy', 'Покупка ценных бумаг'), ('BuyCard', 'Покупка ценных бумаг с банковской карты'), ('Sell', 'Продажа ценных бумаг'), ('Dividend', 'Получение дивидендов'), ('BrokerCommission', 'Комиссия брокера'), ('ServiceCommission', 'Комиссия за обслуживание'), ('Tax', 'Налог'), ('TaxBack', 'Налоговый вычет/корректировка налога'), ('TaxDividend', 'Налог на дивиденды')], default='', max_length=30, verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыта?')),
                ('operations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Operation', verbose_name='Операции')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
        migrations.AddField(
            model_name='operation',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.Currency', verbose_name='Валюта'),
        ),
    ]
