# Generated by Django 3.0.8 on 2020-08-16 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumenttype',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.Currency', verbose_name='Валюта'),
        ),
    ]
