# Generated by Django 3.0.7 on 2020-06-29 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200630_0121'),
        ('market', '0002_auto_20200630_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='investment_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.InvestmentAccount', verbose_name='Инвестиционный счет'),
            preserve_default=False,
        ),
    ]
