# Generated by Django 3.0.8 on 2020-07-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20200723_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='value',
            field=models.DecimalField(decimal_places=6, max_digits=7, verbose_name='Доля'),
        ),
    ]
