# Generated by Django 3.0.8 on 2020-08-15 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('market', '0002_instrumenttype_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealincome',
            name='co_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_income_set', to='users.CoOwner', verbose_name='Совладелец'),
        ),
        migrations.AddField(
            model_name='dealincome',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Deal', verbose_name='Сделка'),
        ),
        migrations.AddField(
            model_name='deal',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.InstrumentType', verbose_name='Ценная бумага'),
        ),
        migrations.AddField(
            model_name='deal',
            name='investment_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='users.InvestmentAccount', verbose_name='Инвестиционный счет'),
        ),
        migrations.CreateModel(
            name='CurrencyInstrument',
            fields=[
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('market.instrumenttype',),
        ),
        migrations.CreateModel(
            name='StockInstrument',
            fields=[
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('market.instrumenttype',),
        ),
        migrations.AddConstraint(
            model_name='instrumenttype',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('isin', ''), ('lot', 0), ('min_price_increment', 0), ('type', ('Currency',)), models.Q(_negated=True, iso_code=''), models.Q(_negated=True, abbreviation='')), models.Q(('abbreviation', ''), ('currency__isnull', False), ('iso_code', ''), ('lot__gte', 1), ('type', 'Stock'), models.Q(_negated=True, isin='')), ('type', 'Unknown'), _connector='OR'), name='instrumenttype_restrict_property_set_by_type'),
        ),
        migrations.AddConstraint(
            model_name='dealincome',
            constraint=models.UniqueConstraint(fields=('deal', 'co_owner'), name='unique_deal_co-owner'),
        ),
    ]
