# Generated by Django 3.0.8 on 2020-08-15 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20200815_0028'),
        ('market', '0003_auto_20200815_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumenttype',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='operations.Currency', verbose_name='Валюта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='lot',
            field=models.PositiveIntegerField(verbose_name='шт/лот'),
        ),
    ]
