# Generated by Django 3.0.7 on 2020-06-30 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_investmentaccount_name'),
        ('market', '0003_operation_investment_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='investment_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.InvestmentAccount', verbose_name='Инвестиционный счет'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figi', models.CharField(max_length=32, unique=True, verbose_name='FIGI')),
                ('ticker', models.CharField(max_length=16, unique=True, verbose_name='Ticker')),
                ('isin', models.CharField(max_length=32, verbose_name='ISIN')),
                ('min_price_increment', models.PositiveSmallIntegerField(verbose_name='Шаг цены')),
                ('lot', models.PositiveIntegerField(verbose_name='шт/лот')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
    ]
