# Generated by Django 3.0.8 on 2020-08-16 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20200816_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.InstrumentType', verbose_name='Ценная бумага'),
        ),
    ]
