# Generated by Django 3.0.8 on 2020-08-18 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('market', '0003_auto_20200818_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='co_owners',
            field=models.ManyToManyField(through='market.DealIncome', to='users.CoOwner'),
        ),
        migrations.AlterField(
            model_name='dealincome',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_set', to='market.Deal', verbose_name='Сделка'),
        ),
    ]
