# Generated by Django 3.0.7 on 2020-06-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20200630_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='min_price_increment',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Шаг цены'),
        ),
    ]
