# Generated by Django 3.0.8 on 2020-07-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20200726_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('PayOut', 'Вывод средств'), ('PayIn', 'Пополнение счета'), ('Buy', 'Покупка ценных бумаг'), ('BuyCard', 'Покупка ценных бумаг с банковской карты'), ('Sell', 'Продажа ценных бумаг'), ('Dividend', 'Получение дивидендов'), ('BrokerCommission', 'Комиссия брокера'), ('ServiceCommission', 'Комиссия за обслуживание'), ('MarginCommission', 'Комиссия за маржинальную торговлю'), ('Tax', 'Налог'), ('TaxBack', 'Налоговый вычет/корректировка налога'), ('TaxDividend', 'Налог на дивиденды')], max_length=30, verbose_name='Тип'),
        ),
    ]
