# Generated by Django 3.0.7 on 2020-07-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20200630_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='payment',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='min_price_increment',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Шаг цены'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Цена/шт.'),
        ),
    ]
