# Generated by Django 3.0.8 on 2020-08-06 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20200729_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Торговый инструмент',
                'verbose_name_plural': 'Торговые инструменты',
            },
        ),
        migrations.RemoveField(
            model_name='operation',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='deal',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='figi',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='investment_account',
        ),
        migrations.RemoveField(
            model_name='share',
            name='co_owner',
        ),
        migrations.RemoveField(
            model_name='share',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='currency',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='figi',
        ),
        migrations.CreateModel(
            name='CurrencyInstrument',
            fields=[
                ('instrumenttype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.InstrumentType')),
                ('figi', models.CharField(default='', max_length=32, verbose_name='figi')),
                ('iso_code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('abbreviation', models.CharField(max_length=16, verbose_name='Знак')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
            bases=('market.instrumenttype',),
        ),
        migrations.CreateModel(
            name='StockInstrument',
            fields=[
                ('instrumenttype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.InstrumentType')),
                ('figi', models.CharField(max_length=32, unique=True, verbose_name='FIGI')),
                ('ticker', models.CharField(max_length=16, unique=True, verbose_name='Ticker')),
                ('isin', models.CharField(max_length=32, verbose_name='ISIN')),
                ('min_price_increment', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Шаг цены')),
                ('lot', models.PositiveIntegerField(verbose_name='шт/лот')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
            bases=('market.instrumenttype',),
        ),
    ]
