# Generated by Django 3.0.7 on 2020-07-10 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20200710_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='deal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='market.Deal', verbose_name='Сделка'),
        ),
    ]
