# Generated by Django 3.0.8 on 2020-08-15 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20200815_0230'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='instrumenttype',
            name='instrumenttype_restrict_property_set_by_type',
        ),
        migrations.RemoveField(
            model_name='instrumenttype',
            name='abbreviation',
        ),
        migrations.RemoveField(
            model_name='instrumenttype',
            name='iso_code',
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='min_price_increment',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Шаг цены'),
        ),
        migrations.AddConstraint(
            model_name='instrumenttype',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('isin', ''), ('lot__gte', 1), ('type', ('Currency',))), models.Q(('lot__gte', 1), ('type', 'Stock'), models.Q(_negated=True, isin='')), ('type', 'Unknown'), _connector='OR'), name='instrumenttype_restrict_property_set_by_type'),
        ),
    ]
