# Generated by Django 3.0.8 on 2020-08-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20200815_0242'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='instrumenttype',
            name='instrumenttype_restrict_property_set_by_type',
        ),
        migrations.AddConstraint(
            model_name='instrumenttype',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('isin', ''), ('lot__gte', 1), ('type__in', ('Currency',))), models.Q(('lot__gte', 1), ('type__in', ('Stock',)), models.Q(_negated=True, isin='')), ('type', 'Unknown'), _connector='OR'), name='instrumenttype_restrict_property_set_by_type'),
        ),
    ]
