# Generated by Django 3.0.7 on 2020-07-10 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200710_0330'),
        ('market', '0006_auto_20200710_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='investment_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='users.InvestmentAccount', verbose_name='Инвестиционный счет'),
        ),
    ]
