# Generated by Django 3.0.8 on 2020-08-06 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200806_2123'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('market', '0006_auto_20200806_2123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
        migrations.DeleteModel(
            name='Share',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_market.instrumenttype_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='deal',
            name='instrument',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='market.InstrumentType', verbose_name='Ценная бумага'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockinstrument',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.CurrencyInstrument', verbose_name='Валюта'),
        ),
    ]
