# Generated by Django 3.0.7 on 2020-07-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20200702_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='min_price_increment',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Шаг цены'),
        ),
    ]
