# Generated by Django 3.0.7 on 2020-07-10 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200710_0330'),
        ('market', '0007_auto_20200710_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Доля')),
                ('co_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CoOwner', verbose_name='Совладелец')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Operation', verbose_name='Операция')),
            ],
            options={
                'verbose_name': 'Доля в операции',
                'verbose_name_plural': 'Доли в операциях',
            },
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.UniqueConstraint(fields=('operation', 'co_owner'), name='unique_co_owner_op'),
        ),
    ]
