# Generated by Django 3.0.7 on 2020-07-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20200702_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='commission',
            field=models.DecimalField(decimal_places=4, max_digits=16, null=True, verbose_name='Комиссия'),
        ),
    ]
