# Generated by Django 3.0.7 on 2020-07-11 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200710_0330'),
        ('market', '0008_auto_20200711_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='co_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='users.CoOwner', verbose_name='Совладелец'),
        ),
        migrations.AlterField(
            model_name='share',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='market.Operation', verbose_name='Операция'),
        ),
    ]
