# Generated by Django 3.0.7 on 2020-07-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20200711_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Доля'),
        ),
    ]
