# Generated by Django 3.0.7 on 2020-07-17 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20200714_0314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='share',
            options={'ordering': ['pk'], 'verbose_name': 'Доля в операции', 'verbose_name_plural': 'Доли в операциях'},
        ),
    ]
