# Generated by Django 3.0.7 on 2020-07-19 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200712_0358'),
        ('market', '0011_auto_20200717_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Доход')),
                ('co_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CoOwner', verbose_name='Совладелец')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Deal', verbose_name='Сделка')),
            ],
            options={
                'verbose_name': 'Доход за сделку',
                'verbose_name_plural': 'Доходы за сделку',
            },
        ),
        migrations.AddConstraint(
            model_name='dealincome',
            constraint=models.UniqueConstraint(fields=('deal', 'co_owner'), name='unique deal co-owner'),
        ),
    ]
