# Generated by Django 3.0.7 on 2020-06-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='production_token',
            field=models.CharField(blank=True, max_length=120, verbose_name='Токен для торговли'),
        ),
        migrations.AddField(
            model_name='investor',
            name='sandbox_token',
            field=models.CharField(blank=True, max_length=120, verbose_name='Токен для песочницы'),
        ),
    ]
