# Generated by Django 3.0.8 on 2020-08-18 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20200818_1241'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coowner',
            name='capital',
        ),
        migrations.RemoveField(
            model_name='coowner',
            name='default_share',
        ),
        migrations.AddField(
            model_name='investmentaccount',
            name='currencies',
            field=models.ManyToManyField(through='users.CurrencyAsset', to='operations.Currency'),
        ),
        migrations.AddField(
            model_name='investmentaccount',
            name='investors',
            field=models.ManyToManyField(through='users.CoOwner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='currencyasset',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='operations.Currency', verbose_name='Валюта'),
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Капитал')),
                ('default_share', models.DecimalField(decimal_places=8, default=0, max_digits=9, verbose_name='Доля по умолчанию')),
                ('co_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_set', to='users.CoOwner', verbose_name='Совладелец')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_set', to='operations.Currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Капитал совладельца',
                'verbose_name_plural': 'Капиталы совладельцев',
            },
        ),
        migrations.AddField(
            model_name='coowner',
            name='currencies',
            field=models.ManyToManyField(through='users.Capital', to='operations.Currency'),
        ),
        migrations.AddConstraint(
            model_name='capital',
            constraint=models.UniqueConstraint(fields=('co_owner', 'currency'), name='unique_capital'),
        ),
    ]
