# Generated by Django 3.0.8 on 2020-08-15 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('market', '0003_auto_20200815_0028'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyasset',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.CurrencyInstrument', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='currencyasset',
            name='investment_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_assets', to='users.InvestmentAccount', verbose_name='Инвестиционный счет'),
        ),
        migrations.AddField(
            model_name='coowner',
            name='investment_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_owners', to='users.InvestmentAccount', verbose_name='Инвестиционный счет'),
        ),
        migrations.AddField(
            model_name='coowner',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_owned_investment_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Инвестор'),
        ),
        migrations.AddField(
            model_name='investor',
            name='default_investment_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.InvestmentAccount', verbose_name='Инвестиционный счет по умолчанию'),
        ),
        migrations.AddField(
            model_name='investor',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='investor',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='investmentaccount',
            constraint=models.UniqueConstraint(fields=('name', 'creator'), name='unique_inv_name'),
        ),
        migrations.AddConstraint(
            model_name='investmentaccount',
            constraint=models.UniqueConstraint(fields=('creator', 'token'), name='unique_token'),
        ),
        migrations.AddConstraint(
            model_name='currencyasset',
            constraint=models.UniqueConstraint(fields=('investment_account', 'currency'), name='unique_currency_asset'),
        ),
        migrations.AddConstraint(
            model_name='coowner',
            constraint=models.UniqueConstraint(fields=('investor', 'investment_account'), name='co_owner_constraints'),
        ),
    ]
