# Generated by Django 3.0.8 on 2020-08-16 01:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentaccount',
            name='sync_at',
            field=models.DateTimeField(default=datetime.datetime(1990, 1, 1, 0, 0, tzinfo=utc), verbose_name='Время последней синхронизации'),
        ),
    ]
