# Generated by Django 3.0.7 on 2020-06-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200628_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='operations_sync_at',
            field=models.DateTimeField(null=True, verbose_name='Время последней синхронизации'),
        ),
    ]
