# Generated by Django 3.0.8 on 2020-08-15 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20200815_0028'),
        ('users', '0002_auto_20200815_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyasset',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.Currency', verbose_name='Валюта'),
        ),
    ]
