# Generated by Django 3.0.7 on 2020-07-06 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('users', '0002_auto_20200706_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Количество')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.Currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Валютный актив',
                'verbose_name_plural': 'Валютные активы',
                'ordering': ('currency',),
            },
        ),
    ]
