# Generated by Django 3.0.8 on 2020-08-19 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20200818_1241'),
        ('users', '0002_auto_20200818_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capital',
            options={'ordering': ('currency',), 'verbose_name': 'Капитал совладельца', 'verbose_name_plural': 'Капиталы совладельцев'},
        ),
        migrations.AlterField(
            model_name='capital',
            name='co_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital', to='users.CoOwner', verbose_name='Совладелец'),
        ),
        migrations.AlterField(
            model_name='capital',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital', to='operations.Currency', verbose_name='Валюта'),
        ),
    ]
