# Generated by Django 3.0.8 on 2020-07-27 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200726_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coowner',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_owned_investment_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Инвестор'),
        ),
        migrations.AlterField(
            model_name='investmentaccount',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_investment_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Создатель счета'),
        ),
    ]
