# Generated by Django 3.0.7 on 2020-07-06 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_currencyasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyasset',
            name='investment_account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.InvestmentAccount', verbose_name='Инвестиционный счет'),
            preserve_default=False,
        ),
    ]
