# Generated by Django 3.0.7 on 2020-06-29 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200628_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital_sharing_principle', models.CharField(choices=[('Abs', 'Абсолютный'), ('Rel', 'Относительный')], max_length=16, verbose_name='Принцип разделения капитала')),
                ('co_owners', models.ManyToManyField(related_name='co_owned_investor_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Совладельцы')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_investor_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Создатель счета')),
            ],
            options={
                'verbose_name': 'Инвесторский счет',
                'verbose_name_plural': 'Инвесторские счета',
            },
        ),
    ]
