# Generated by Django 3.0.7 on 2020-06-29 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_investoraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, verbose_name='Токен для торговли')),
                ('broker_account_id', models.CharField(max_length=50, verbose_name='ID инвестиционного счета')),
                ('operations_sync_at', models.DateTimeField(null=True, verbose_name='Время последней синхронизации')),
                ('capital_sharing_principle', models.CharField(choices=[('Abs', 'Абсолютный'), ('Rel', 'Относительный')], max_length=16, verbose_name='Принцип разделения капитала')),
            ],
            options={
                'verbose_name': 'Инвестиционный счет',
                'verbose_name_plural': 'Инвестиционные счета',
            },
        ),
        migrations.RemoveField(
            model_name='investor',
            name='operations_sync_at',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='production_token',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='sandbox_token',
        ),
        migrations.DeleteModel(
            name='InvestorAccount',
        ),
        migrations.AddField(
            model_name='investmentaccount',
            name='co_owners',
            field=models.ManyToManyField(related_name='co_owned_investor_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Совладельцы'),
        ),
        migrations.AddField(
            model_name='investmentaccount',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_investor_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Создатель счета'),
        ),
    ]
