# Generated by Django 3.0.7 on 2020-07-09 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200706_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentaccount',
            name='co_owners',
        ),
        migrations.CreateModel(
            name='CoOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Капитал')),
                ('share', models.PositiveIntegerField(default=0, verbose_name='Доля')),
                ('investment_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_owners', to='users.InvestmentAccount', verbose_name='Инвестиционный счет')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_owned_investor_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Совладелец')),
            ],
            options={
                'verbose_name': 'Совладелец',
                'verbose_name_plural': 'Совладельцы',
            },
        ),
    ]
