# Generated by Django 3.0.7 on 2020-06-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200630_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentaccount',
            name='name',
            field=models.CharField(default='', max_length=256, verbose_name='Название счета'),
            preserve_default=False,
        ),
    ]
