# Generated by Django 3.0.7 on 2020-06-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_investmentaccount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentaccount',
            name='capital_sharing_principle',
            field=models.CharField(choices=[('abs', 'Абсолютный'), ('rel', 'Относительный')], max_length=16, verbose_name='Принцип разделения капитала'),
        ),
    ]
