# Generated by Django 3.0.7 on 2020-07-09 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200709_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coowner',
            name='share',
        ),
        migrations.AddField(
            model_name='coowner',
            name='default_share',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Доля по умолчанию'),
        ),
        migrations.AlterField(
            model_name='coowner',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_owned_investor_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Инвестор'),
        ),
    ]
