# Generated by Django 3.0.7 on 2020-07-01 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_investor_default_investment_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='default_investment_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.InvestmentAccount', verbose_name='Инвестиционный счет по умолчанию'),
        ),
    ]
