# Generated by Django 3.0.7 on 2020-07-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200710_0101'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coowner',
            constraint=models.UniqueConstraint(fields=('investor', 'investment_account'), name='co_owner_constraints'),
        ),
    ]
