# Generated by Django 3.0.7 on 2020-07-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200710_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentaccount',
            old_name='operations_sync_at',
            new_name='sync_at',
        ),
        migrations.RemoveField(
            model_name='investmentaccount',
            name='capital_sharing_principle',
        ),
        migrations.AddConstraint(
            model_name='currencyasset',
            constraint=models.UniqueConstraint(fields=('investment_account', 'currency'), name='unique_currency_asset'),
        ),
        migrations.AddConstraint(
            model_name='investmentaccount',
            constraint=models.UniqueConstraint(fields=('name', 'creator'), name='unique_inv_name'),
        ),
        migrations.AddConstraint(
            model_name='investmentaccount',
            constraint=models.UniqueConstraint(fields=('creator', 'token'), name='unique_token'),
        ),
    ]
