# Generated by Django 3.0.7 on 2020-07-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200710_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coowner',
            name='default_share',
            field=models.PositiveIntegerField(default=0, verbose_name='Доля по умолчанию'),
        ),
    ]
